config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'feed#show'

  get 'sign_up',  to: 'users#new'
  post 'sign_up', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'
  resource :profile, only: %i[show update], controller: 'users'

  namespace :users do
    patch 'change_password', to: 'passwords#update'
    resources :password_resets, only: %i[new create edit update]
  end

  resources :listings, except: :index
  resource :my_listings, only: :show
end

app/models/listing.rb
# frozen_string_literal: true

class Listing < ApplicationRecord
  include HasAddress
  include PermittedAttributes

  belongs_to :creator, class_name: 'User'
  belongs_to :organization

  has_one_attached :cover_photo
  has_rich_text :description

  scope :feed, lambda {
    order(created_at: :desc).includes(:address).with_attached_cover_photo
  }

  enum condition: {
    brand_new: 'brand_new',
    like_new: 'like_new',
    used: 'used',
    not_working: 'not_working'
  }

  validates :title, length: { in: 10..100 }
  validates :price, numericality: { only_integer: true }
  validates :condition, presence: true
  validates :tags, length: { in: 1..5 }
  validates :cover_photo, presence: true
  validates :description, presence: true

  before_save :downcase_tags

  private

  def downcase_tags
    self.tags = tags.map(&:downcase)
  end
end

app/models/listing/permitted_attributes.rb
# frozen_string_literal: true

module Listing::PermittedAttributes
  extend ActiveSupport::Concern

  class_methods do
    def permitted_attributes
      [
        :title, :price, :condition, :cover_photo, :description, {
          tags: [],
          address_attributes: Address.permitted_attributes
        }
      ]
    end
  end
end

app/controllers/listings_controller.rb
# frozen_string_literal: true

class ListingsController < ApplicationController
  before_action :load_listing, except: %i[new create]
  allow_unauthenticated only: :show

  def show; end

  def new
    @listing = Listing.new
    @listing.build_address
  end

  def edit; end

  def create
    @listing = Listing.new(
      listing_params.with_defaults(
        creator: Current.user,
        organization: Current.organization
      )
    )

    if @listing.save
      redirect_to listing_path(@listing),
                  flash: { success: t('.success') },
                  status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @listing.update(listing_params)
      redirect_to listing_path(@listing),
                  status: :see_other,
                  flash: { success: t('.success') }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @listing.destroy!
    flash[:success] = t('.success')
    redirect_to my_listings_path,
                status: :see_other
  end

  private

  def listing_params
    params.require(:listing).permit(
      Listing.permitted_attributes
    )
  end

  def load_listing
    @listing = Listing.find(params[:id])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="flex flex-col md:flex-row md:justify-center md:gap-20">
  <div class="flex flex-col gap-4">
    <div class="block relative"> 
      <%= form.label :title, class: "block text-gray-600 cursor-text text-sm leading-[140%] font-normal mb-2" %>
      <%= form.text_field :title, class: "rounded border border-gray-200 text-sm w-full font-normal leading-[18px] text-black tracking-[0px] appearance-none block h-11 m-0 p-[11px] focus:ring-2 ring-offset-2  ring-gray-900 outline-0" %>
    </div>
    <div class="block relative mb-14"> 
      <%= form.label :description, class: "block text-gray-600 cursor-text text-sm leading-[140%] font-normal mb-2" %>
      <%= form.rich_text_area :description, class: "mb-4"%>
    </div>
    <%= render \
        "shared/image_field",
        form: form,
        attribute: :cover_photo,
        label: t(".cover_photo") %>
    <div class="relative flex"> 
      <div class="flex flex-col">
        <div class="block relative"> 
          <%= form.label :price, class: "block text-gray-600 cursor-text text-sm leading-[140%] font-normal mb-2" do%>
            Price NRS
          <% end%>
          <%= form.text_field(
            :price,
            inputmode: :numeric,
            class: "rounded border border-gray-200 text-sm w-full font-normal leading-[18px] text-black tracking-[0px] appearance-none block h-11 m-0 p-[11px] focus:ring-2 ring-offset-2  ring-gray-900 outline-0"
          )%>
        </div>
      </div>
    </div>
    <div class="block relative"> 
      <%= form.label :condition, class: "block text-gray-600 cursor-text text-sm leading-[140%] font-normal mb-2" %>
      <%= form.select :condition, Listing.human_enum_options(:condition), {}, class: "rounded border border-gray-200 text-sm w-full font-normal leading-[18px] text-black tracking-[0px] block h-11 m-0 p-[11px] focus:ring-2 ring-offset-2  ring-gray-900 outline-0" %>
    </div>
    <div class="block relative">
      <%= render "tags_field", form: form %>
    </div>
  </div>
  <div class="field flex flex-col gap-4">
    <%= form.label :address, class: "block text-gray-700 cursor-text text-md leading-[140%] font-normal mb-2" %>
    <%= render "addresses/fields", form: form %>
  </div>
</div>

app/views/listings/_listing.html.erb
<div class="relative flex w-80 flex-col rounded-xl bg-clip-border text-gray-700 shadow-md bg-gray-50">
  <div class="relative mx-4 -mt-6 h-40 overflow-hidden rounded-xl bg-blue-gray-500 bg-clip-border text-white shadow-lg shadow-blue-gray-500/40 bg-gradient-to-r from-blue-500 to-blue-600">
    <%= link_to listing_path(listing) do %>
  <figure class="relative image overflow-hidden aspect-w-4 aspect-h-3">
    <% if listing.cover_photo.present? %>
      <%= image_tag listing.cover_photo.variant(
            resize_to_fit: [500, 500]
          ), class: "object-cover object-center w-full h-full" %>
    <% end %>
  </figure>
<% end %>

  </div>
  <div class="p-6">
    <h5 class="mb-2 block font-sans text-xl font-semibold leading-snug tracking-normal text-blue-gray-900 antialiased">
      <%= listing.title %>
    </h5>
    <div class="flex gap-0.5 flex-wrap">
      <%= render "listings/tags", listing: listing %>
    </div>
  </div>
  <div class="p-6 pt-0">
    <div class="mb-1">NRS <%= listing.price %></div>
    <span class="bg-blue-200 rounded-md p-2">
      <%= listing.human_enum_value(:condition) %>
    </span>
  </div>
  <div class="flex items-center text-sm justify-end p-2">
    <%= svg("location", class: "w-4 h-4", fill: "#444") %>
    <span>
      <%= listing.address.redacted %>
    </span>
  </div>
</div>

app/views/listings/_tag.html.erb
<% form = local_assigns[:form] %>
<ui-tag 
  class="control tags bg-gray-200 p-2 rounded-md ml-2"
  data-controller="remove-element">
  <%= tag.span class: "tag" do %>
    #<%= value %>
  <% end %>
  <% if form.present? %>
    <%= form.fields_for(:tags) do |fields| %>
      <%= fields.hidden_field nil, id: nil, value: value %>
    <% end %>
    <a class="tag is-delete cursor-pointer text-red-500", data-action="remove-element#remove">x</a>
  <% end %>
</ui-tag>

app/views/listings/_tags.html.erb
<% listing.tags.each do |value| %>
  <%= render "listings/tag", value: value %>
<% end %>

app/views/listings/_tags_field.html.erb
<div 
  class="flex flex-col gap-2"
  data-controller="tags"
>
  <%= form.label :tags, class: "block text-gray-600 cursor-text text-sm leading-[140%] font-normal" %>
  <p class="mb-2">
    <%= t(".description") %>
  </p>
  <div
    class="mb-2"
    data-tags-target="container"
  >
    <% form.object.tags.each do |value| %>
      <%= render "tag", value: value, form: form %>
    <% end if form.object.tags.present? %>
  </div>
  <div class="flex gap-2 w-full">
    <div class="control">
      <%= text_field_tag nil, nil,
        data: { tags_target: "input" }, class: "rounded border border-gray-200 text-sm w-full font-normal leading-[18px] text-black tracking-[0px] appearance-none block h-11 m-0 p-[11px] focus:ring-2 ring-offset-2  ring-gray-900 outline-0" %>
    </div>
    <div class="control">
      <button 
        class="button is-info bg-black text-white border-none rounded-md p-2 font-bold cursor-pointer hover:bg-gray-500"
        type="button"
        data-action="tags#addTag"
      >
        <%= t(".add_tag") %>
      </button>
    </div>
  </div>
  <%= tag.p class: "error-text" do %>
    <%= form.object.errors.messages_for(:tags).to_sentence %>
  <% end if form.object.errors.include?(:tags) %>
  <template data-tags-target="template">
    <%= render "tag", value: "{value}", form: form %>
  </template>
</div>

app/views/listings/edit.html.erb
<%= content_for :title, @listing.title %> 

<div class="relative flex flex-col p-4 rounded-md text-black bg-white m-auto mt-4 md:mt-32 items-center">
  <%= form_with(
    model: @listing,
    class: "flex flex-col gap-3",
    id: "edit_listing_form",
  ) do |form| %>
    <%= render "form", form: form %>
  <% end %>
  <div class="flex justify-center gap-10 mt-8">
    <%= button_to t(".delete"),
      listing_path(@listing),
      method: :delete,
      form: { data: {
        turbo_confirm: t(".confirm_delete")
      }},
      class: "px-4 py-2 bg-red-500 text-white rounded-md m-3" %>
    <%= submit_tag t(".publish"),
      form: "edit_listing_form",
      class: "px-4 py-2 bg-blue-500 text-white rounded-md m-3" %>
  </div>
</div>

app/views/listings/new.html.erb
<%= content_for :title, t(".title") %> 
<div class="relative flex flex-col p-4 rounded-md text-black bg-white m-auto mt-4 md:mt-4 items-center">
  <%= form_with(
    model: @listing,
    class: "flex flex-col gap-3",
    id: "new_listing_form",
  ) do |form| %>
    <%= render "form", form: form %>
  <% end %>
  <div class="mt-8 cursor-pointer">
    <%= submit_tag(
      t(".publish"),
      form: "new_listing_form",
      class: "bg-[#7747ff] w-max m-auto px-6 py-2 rounded text-white text-sm font-normal"
    )%>
  </div>
</div>

app/views/listings/show.html.erb
<%= content_for :title, @listing.title %>
<div class="m-auto flex flex-col items-center mt-10 md:mt-40">
  <div class="ml-auto grid grid-cols-1 justify-center md:grid-cols-1 lg:grid-cols-3 w-[80%]">
    <div class="col-span-1 md:col-span-1 lg:col-span-2">
      <div class="mb-3">
        <h1 class="inline-block text-2xl font-bold">
          <%= @listing.title %>
        </h1>
        <%= link_to t(".edit"), edit_listing_path(@listing), class: "text-blue-500 ml-3" %>
      </div>
      <%= render "tags", listing: @listing %>
      <div class="text-center">
        <%= link_to url_for(@listing.cover_photo) do %>
          <figure class="inline-block">
            <%= image_tag @listing.cover_photo.variant(
              resize_to_limit: [800, 800]
            ), class: "w-full" %>
        </figure>
      <% end %>
      </div>

      <div class="grid grid-cols-1 justify-center md:grid-cols-2 lg:grid-cols-2 gap-4">
        <div class="bg-white rounded-md shadow-md p-5 mt-6">
          <dl>
            <dt class="text-gray-600">
              <%= t(".posted_by") %>
            </dt>
            <dd class="font-semibold text-lg">
              <%= @listing.creator.name %>
            </dd>
          </dl>

          <div class="mt-6 flex">
            <%= button_to "#", class: "px-4 py-2 bg-gray-200 text-gray-800 rounded-md mr-3 flex items-center gap-2" do %>
              <%= svg("heart", class: "w-4 h-4", fill: "#111827") %>
              <%= t(".save") %>
            <% end %>

            <%= link_to "#", class: "px-4 py-2 bg-blue-500 text-white rounded-md flex items-center gap-2" do %>
              <%= svg("message", class: "w-4 h-4", fill: "white") %>
              <%= t(".contact") %>
            <% end %>
          </div>
        </div>

        <div class="bg-white rounded-md shadow-md p-5 mt-6 flex justify-between">
          <div>
            <dl>
              <dt class="text-gray-600">
                <%= Listing.human_attribute_name(:price) %>
              </dt>
              <dd class="font-semibold text-lg">
                <%= "#{@listing.price} NRS" %>
              </dd>
            </dl>
            <dl>
              <dt class="text-gray-600">
                <%= Listing.human_attribute_name(:condition) %>
              </dt>
              <dd class="font-semibold text-lg">
                <%= @listing.human_enum_value(:condition) %>
              </dd>
            </dl>
          </div>
          <div>
            <dl>
              <dt class="text-gray-600">
                <%= t(".location") %>
              </dt>
              <dd class="font-semibold text-lg">
                <%= @listing.address.redacted %>
              </dd>
            </dl>
          </div>
        </div>
      </div>
      <div class="mt-4">
        <%= @listing.description %>
      </div>
    </div>
  </div>
</div>