config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'feed#show'

  get 'sign_up',  to: 'users#new'
  post 'sign_up', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'
  resource :profile, only: %i[show update], controller: 'users'

  namespace :users do
    patch 'change_password', to: 'passwords#update'
    resources :password_resets, only: %i[new create edit update]
  end

  resources :listings, except: :index
  resource :my_listings, only: :show
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  include PermittedAttributes
  belongs_to :addressable, polymorphic: true

  attribute :country, default: 'NP'

  validates :line_1, presence: true
  validates :line_2, presence: true
  validates :city, presence: true
  validates :postcode, presence: true
  validates :country, presence: true

  def redacted
    "#{city}, #{postcode}"
  end
end

app/models/app_session.rb
# frozen_string_literal: true

class AppSession < ApplicationRecord
  belongs_to :user

  has_secure_password :token, validations: false

  before_create :create_token

  def to_h
    {
      user_id: user.id,
      app_session: id,
      token: token
    }
  end

  private

  def create_token
    self.token = self.class.generate_unique_secure_token
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  include MessageVerifier
  include HumanEnum

  primary_abstract_class
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user, :app_session, :organization
end

app/models/listing.rb
# frozen_string_literal: true

class Listing < ApplicationRecord
  include HasAddress
  include PermittedAttributes

  belongs_to :creator, class_name: 'User'
  belongs_to :organization

  has_one_attached :cover_photo
  has_rich_text :description

  scope :feed, lambda {
    order(created_at: :desc).includes(:address).with_attached_cover_photo
  }

  enum condition: {
    brand_new: 'brand_new',
    like_new: 'like_new',
    used: 'used',
    not_working: 'not_working'
  }

  validates :title, length: { in: 10..100 }
  validates :price, numericality: { only_integer: true }
  validates :condition, presence: true
  validates :tags, length: { in: 1..5 }
  validates :cover_photo, presence: true
  validates :description, presence: true

  before_save :downcase_tags

  private

  def downcase_tags
    self.tags = tags.map(&:downcase)
  end
end

app/models/membership.rb
# frozen_string_literal: true

class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
  has_many :listings
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include PasswordReset

  has_many :memberships, dependent: :destroy
  has_many :organizations, through: :memberships
  has_many :app_sessions, dependent: :destroy
  has_secure_password

  validates :name, presence: true
  validates :email,
            format: { with: URI::MailTo::EMAIL_REGEXP },
            uniqueness: { case_sensitive: false }
  validates :password,
            on: %i[create password_change],
            presence: true,
            length: { minimum: 8 }

  before_validation :strip_extra_space

  def self.create_app_session(email:, password:)
    user = find_by(email: email.downcase)
    return unless user

    user.app_sessions.create! if user.authenticate(password)
  end

  def authenticate_app_session(app_session_id, token)
    app_sessions.find(app_session_id).authenticate_token(token)
  rescue ActiveRecord::RecordNotFound
    nil
  end

  private

  def strip_extra_space
    self.name = name&.strip
    self.email = email&.strip
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Authenticate
  include SetCurrentRequestDetails

  include Pagy::Backend

  helper_method :turbo_frame_request?
end

app/controllers/feed_controller.rb
# frozen_string_literal: true

class FeedController < ApplicationController
  allow_unauthenticated

  def show
    @pagy, @listings = pagy(Listing.feed)
  end
end

app/controllers/listings_controller.rb
# frozen_string_literal: true

class ListingsController < ApplicationController
  before_action :load_listing, except: %i[new create]
  allow_unauthenticated only: :show

  def show; end

  def new
    @listing = Listing.new
    @listing.build_address
  end

  def edit; end

  def create
    @listing = Listing.new(
      listing_params.with_defaults(
        creator: Current.user,
        organization: Current.organization
      )
    )

    if @listing.save
      redirect_to listing_path(@listing),
                  flash: { success: t('.success') },
                  status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @listing.update(listing_params)
      redirect_to listing_path(@listing),
                  status: :see_other,
                  flash: { success: t('.success') }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @listing.destroy!
    flash[:success] = t('.success')
    redirect_to my_listings_path,
                status: :see_other
  end

  private

  def listing_params
    params.require(:listing).permit(
      Listing.permitted_attributes
    )
  end

  def load_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_authentication only: %i[new create]

  def new; end

  def create
    @app_session = User.create_app_session(
      email: login_params[:email],
      password: login_params[:password]
    )
    if @app_session
      log_in(@app_session)
      flash[:success] = t('.success')
      redirect_to root_path, status: :see_other
    else
      flash.now[:danger] = t('.incorrect_details')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    log_out

    flash[:success] = t('.success')
    redirect_to root_path, status: :see_other
  end

  private

  def login_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_authentication only: %i[new create]

  def show
    @user = Current.user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @organization = Organization.create!(members: [@user])
      @app_session = @user.app_sessions.create!
      log_in(@app_session)
      redirect_to root_path,
                  status: :see_other,
                  flash: { success: t('.welcome', name: @user.name) }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @user = Current.user
    if @user.update(user_params)
      flash[:success] = t('.success')
      redirect_to profile_path, status: :see_other
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend

  def title
    return t('kibe') unless content_for(:title)

    "#{content_for(:title)} | #{t('kibe')}"
  end

  def flash_class(level)
    case level
    when 'success'
      'max-w-2xl bg-green-300 px-4 py-3 m-auto'
    when 'danger'
      'max-w-2xl bg-red-300 px-4 py-3 m-auto'
    else
      'max-w-2xl bg-blue-300 px-4 py-3 m-auto'
    end
  end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/my_listings_helper.rb
module MyListingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/svg_helper.rb
# frozen_string_literal: true

module SvgHelper
  def svg(svg_name, **attributes)
    svg_markup =
      render file:
        Rails.root.join("app/views/shared/svg/#{svg_name}.svg").to_s

    xml = Nokogiri::XML(svg_markup)
    attributes&.each do |key, value|
      xml.root.set_attribute(key, value)
    end

    xml.root.to_xml.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" if flash.present? %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flashes.html.erb
  <% flash.each do |level, message| %>
    <div class="<%= flash_class(level) %> notification" data-turbo-cache="false">
      <span class="block sm:inline"><%= message %></span>
    </div>
  <% end %>

app/views/shared/_image_field.html.erb
<%= tag.image_upload_field(
  data: {
    controller: "image-upload",
    image_upload_blob_url_template_value: rails_service_blob_url(":signed_id", ":filename"),
  }
) do %>
  <div class="flex items-center justify-center bg-gray-100 p-4 rounded-lg">
    <label class="relative cursor-pointer" data-image-upload-target="cta">
      <%= form.file_field(
            nil,
            id: nil,
            class: "opacity-0",
            accept: "image/*",
            direct_upload: true,
            required: true,
            data: {
              action: "image-upload#upload",
              image_upload_target: "fileInput"
            }
      ) %>
      <%= form.hidden_field(
            attribute,
            value: form.object.cover_photo&.signed_id,
            data: {
              image_upload_target: "hiddenInput"
            }
      ) %>


      <div class="flex flex-col items-center justify-center text-center">
        <%= svg "upload", class: "w-12 h-12" %>
        <span class="text-sm font-medium text-gray-600">
          <%= label %>
        </span>
      </div>
    </label>
  </div>
  <figure class="relative">
    <% url = form.object.cover_photo.present? ? url_for(form.object.cover_photo) : "" %>
    <%= image_tag(url, data: { image_upload_target: "preview" }) %>
  </figure>
  <progress value="0" max="100" class="w-full bg-blue-500" data-image-upload-target="progress">
  </progress>
  <%= tag.div(
      class: "flex justify-center hidden mt-3",
      data: { image_upload_target: "remove" }
    ) do %>
    <%= tag.button(
          class: "px-4 py-2 bg-red-500 text-white rounded-md",
          type: "button",
          data: { action: "image-upload#remove" }
        ) do %>
      <%= t(".remove_image") %>
    <% end %>
  <% end %>

<% end %>

app/views/shared/_navbar.html.erb
<header class="flex flex-wrap md:justify-start md:flex-nowrap z-50 w-full text-sm">
  <nav 
    class="mt-6 bg-gray-200 relative max-w-[85rem] w-full border border-gray-200 rounded-[36px] mx-2 py-3 px-4 md:flex md:items-center md:justify-between md:py-0 md:px-6 lg:px-8 xl:mx-auto"
    aria-label="Global"
    data-controller="navbar"
  >
    <div class="flex items-center justify-between">
      <%= link_to 'Kibe Pasal', root_path, class: "flex-none text-xl font-semibold" %>
      <div class="md:hidden">
        <button 
          aria-controls="navbar-collapse-with-animation"
          aria-label="Toggle navigation"
          type="button"
          class="navbar-burger hs-collapse-toggle w-8 h-8 flex justify-center items-center text-sm font-semibold rounded-full border border-gray-200 text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none" 
          data-navbar-target="burger"
          data-action="navbar#toggle"
        >
          <svg class="hs-collapse-open:hidden flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="3" x2="21" y1="6" y2="6"/><line x1="3" x2="21" y1="12" y2="12"/><line x1="3" x2="21" y1="18" y2="18"/></svg>
          <svg class="hs-collapse-open:block hidden flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
        </button>
      </div>
    </div>
    <div 
      id="navbar-collapse-with-animation" 
      class="hs-collapse hidden overflow-hidden transition-all duration-300 basis-full grow md:block"
      data-navbar-target="menu"
    >
      <div class="flex flex-col gap-y-4 gap-x-0 mt-5 md:flex-row md:items-center md:justify-end md:gap-y-0 md:gap-x-7 md:mt-0 md:ps-7">
        <%= link_to t(".create_add"), new_listing_path, class: "font-medium text-gray-500 hover:text-gray-400 md:py-6" %>
        <%= link_to t(".message"), "#", class: "font-medium text-gray-500 hover:text-gray-400 md:py-6" if logged_in? %>
        <% if logged_in? %>
          <div class="hs-dropdown md:py-4">
            <%= link_to  profile_path, class: "flex peer items-center w-full text-gray-500 hover:text-gray-400 font-medium" do %>
              <span id="current_user_name">
                <%= Current.user.name %>
              </span>
              <svg class="ms-2 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg>
            <% end %>
            <div class="hidden navbar-dropdown peer-hover:block hover:block transition-[opacity,margin] duration-[0.1ms] md:duration-[150ms]  md:w-48 z-10 bg-white md:shadow-md rounded-lg p-2 absolute top-[60%] md:border left-[85%]">
              <%= link_to t(".profile"), profile_path, class: "flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500" %>
              <%= link_to t(".my_adds"), my_listings_path, class: "flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500" %>
              <%= link_to t(".saved_adds"), "#", class: "flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500" %>
              <%= link_to t(".logout"), 
                logout_path, 
                class: "flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500",
                data: { turbo_method: :delete }
              %>
            </div>
          </div>
        <% else %>
          <%= link_to t(".sign_up"), sign_up_path, class: "flex items-center gap-x-2 font-medium text-gray-500 hover:text-blue-600 md:border-s md:border-gray-300 md:my-6 md:ps-6" %>
          <%= link_to t(".log_in"), login_path, class: "flex items-center font-medium text-gray-500 hover:text-blue-600 md:my-2 md:ps-2" %>
        <% end %>
      </div>
    </div>
  </navaria-label>
</header>